name: rockscope_analyzer
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:       # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  
  # 🚨 CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
  sizer: ^3.0.0              # Required for responsive design system
  flutter_svg: ^2.0.9        # Required for SVG icon support
  google_fonts: ^6.1.0       # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2 # Required for local data storage
  web: ^1.1.1
  
  # State Management & Architecture
  flutter_riverpod: ^2.5.1   # Type-safe state management
  riverpod_annotation: ^2.3.5 # Code generation for providers
  hive: ^2.2.3               # Offline-first local database
  hive_flutter: ^1.1.0       # Hive Flutter integration
  
  # Responsive & PWA
  flutter_adaptive_scaffold: ^0.1.10 # Responsive layouts
  visibility_detector: ^0.4.0+2      # Lazy loading detection
  web_smooth_scroll: ^1.1.0          # Smooth web scrolling
  
  # Performance & Caching
  cached_network_image: ^3.3.1
  dio: ^5.4.3                # Enhanced HTTP client
  
  # Feature dependencies
  connectivity_plus: ^6.1.4
  fluttertoast: ^8.2.4
  fl_chart: ^1.0.0
  camera: ^0.11.2
  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  record: ^6.0.0
  geolocator: ^14.0.2
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  
  # Touch & Gesture optimization
  flutter_widget_from_html: ^0.15.2  # Rich text rendering
  collection: ^1.18.0                # Enhanced collections

dev_dependencies:
  flutter_test:    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter   # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^6.0.0 # 🚨 CRITICAL: Required for code quality - DO NOT REMOVE
  
  # Code generation and build tools
  build_runner: ^2.4.13      # Code generation runner
  riverpod_generator: ^2.4.3 # Riverpod code generation
  hive_generator: ^2.0.1     # Hive type adapters
  json_annotation: ^4.9.0    # JSON serialization
  json_serializable: ^6.8.0  # JSON code generation

flutter:
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/
    - assets/images/
  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)
  
  # 🚨 CRITICAL FONTS RULE: 
  # - THIS PROJECT USES GOOGLE FONTS INSTEAD OF LOCAL FONTS
  # - DO NOT ADD ANY LOCAL FONTS SECTION OR FONT FILES
